language: ruby
cache:
  bundler: true
  yarn: true
  directories:
    - node_modules

addons:
  postgresql: "9.6"

services:
  - postgresql

before_install:
  - nvm install 10

before_script:
  - yarn install
  - RAILS_ENV=test bundle exec rake db:setup

deploy:
  provider: heroku
  app: soldn-staging
  api_key:
    secure: hQX2Ott48/oDxWgireCEyCFwX06T4coeF2I95aRWAhL5oGJWCM7UQ3DkO3CapZ0I5llYMY15kgcFFh7hzifiqR1sesExiie+6SYmoxOKMXi6nVAFh2fE3ogm3qyTzqoA+p5iujgimSukBK+KDA7HwNHz6bPZ1AqOu1OAKJfwoLILq61bUGy2r/cpYlJNs2IQuVR0o/JCXBKrhU2Orpi90/9umewNQX6yFrg3uFAU0YZJ46wwlJvPt1QRw9Pi5D9X9zMIctpcV8fAe3riBNF/9pPjtXew5qFJVw+L7eh3iHRc+kzGaPtaWCc3AXkpVKJ02B7O1O4hn0eS7CfwDHy3J7/0ViH5t3hJBvB4BEdcRMQo3/MD9DJAeyKsR9qOuaC7ji9fnwRJsDElpo6JiTuQECRtovQCMX5tmj+EFwizYryYW7TIKkYdy8XNNsx7kpiuCPsGyp+d7/fmyvEAsEJAZ30Cujf9X1R8gA0+wcfk3SJRd37dkiejg1TcUZoH1l6mt9TTuQUHs9H71fi/SAqc2wECx5hOxOB2Ui+SgyUbMLvVRrnZWbUVmf759ZWldo6QlXiaEeZ2UanGtywc3Dzq+YP2yM+DZrbNzcr3KRC/PlY7sAqbu7Ry+VyikoM7vQ93mcE6WHn9Pef5UbPbJBHoBwxsLjoNC4GrBwva/IOIzaI=
