language: ruby
cache:
  bundler: true
  yarn: true
  directories:
    - node_modules

addons:
  postgresql: "9.6"

services:
  - postgresql

before_install:
  - nvm install 10

before_script:
  - yarn install
  - RAILS_ENV=test bundle exec rake db:setup

deploy:
  provider: heroku
  app: soldn-staging
  api_key:
    secure: Ubgs3KGqUeeJ/LDWEChqTMFng2otLj/Sn44Ate5I4Q7NCPmLx5jSxYwW1Qr1QRVoOMhORl2szKxeqfuUBrI/jnMwSZV5kQ1zdOYGrJbGBBW+TooKuuX8fknNPdWrrfOj108tPQf75YE8+cBN5p6DHW3+ZABLSaK5kNr+dyxXev6CoPv+FvVivCpS3f9mbl+lVSMnmp9dURXKMnkasCSnkfbFh7MYGv81HiVp7em+Ncc6j1BTEohbejg2eDSbiDGihFRrUUVqOLpQlwq7BvKGuQVrjf6eIkuyagn5wuRntWrzmpbogHy022aruYKQpNrg04JwSRtGJ8w+VH10thSpOU0cAvnB1Ryi8OrPTzpmS+7r/EXLUtvGG+7rwOcldPx6uvo/yNns1di+Q+w7W7YCIm3f8JxmwI1EE6Ap29eI9wxXpnyEB9HsNtXXBbRuWQqjE5vdWZz13bMkFmYfIIrmnh4ipbUny+zzAOqdUJnEDT04TQ9KGQ99Rqi0D40vjMwvdvcwb70RKam6uibozW/ZCKTRx37EuVaJvyk/r4a5GpVd/7cEN7xFlxpwuEkR77Vv/R3L8zzhZeSERzChJXJP285bXo6h86z6W2VpxJzcSSVKaFYH54+9NWwDNR6IPPfD7I7fS3UsK/4okmA1ezivXcZQVOkWNzyfnLfQfwHaOfg=
