language: ruby
cache: bundler

services:
  - postrgesql

env:
  - IP_BLOCKLIST=1.1.1.1

before_script:
  - RAILS_ENV=test bundle exec rake db:setup

deploy:
  api_key:
    secure: XmoCA/F3zwt8hmQWKv9oudty1l24o8yKtPUp7lwURJAmtMHV9g5Z8Wgsb10nNC9f4axf6DyEOtl2KRSWhA+LsnnvcjyoxJ1GvKS1EXATeZpRA9SbrcFrPOvlTQp4YF+6xWy1Ngaj9oQNL2zwX1ZuhFE1LNsCUNQB2OfwVbsVg9+VpwkzTZRZdp4BtLanlEtT/vuqcYdJRbXo/tOCbZ5qwfUcwYP0WjGTSKoTQcfqMTW9LOBkyFvSURGvvZZqBaB0IDqK0ziqkZn2JiAnZTEmef5SRodqsfsSk2alDzr+pq+Fsit3Oli2maT1HvZAN7mkkMh/VsjOymxm5B+TNyBx0KcUrdmKVXpB+nS2WDrOMUx7Kb+/5jE2dCrdgpTDuomUvwuURnyaqUVFnuw9zSX84R69nQsMC2aqPBZ9a54wDVs4dc6Z82c+YGJNpOKtty+wOOtZw8a7wUXv1I7IlydPWuT+PlgRimag1pOi4pEZ0R373HGX5VKeomJQDOuLzXn+rJMBbBJuzgBVmXj9ECns2bzk77P9b23bjkXVUX5PZ7Z6Jkjsyf6fB22as9GGRbc7WvgsOknEo3Cd6cwSnNMHSiUP7y/kEGOZ7WR1GWjkxonX98jlPzS55f658pcapZuvU3VuzOwI8oSG5OrNu1/6hwzkTwYm46Q445N5JdebIYU=
  app: soldn-staging
