language: ruby
cache: bundler

services:
  - postrgesql

before_script:
  - RAILS_ENV=test bundle exec rake db:setup

deploy:
  provider: heroku
  api_key:
    secure: K8swUUA7GLYjlIxFB/SjyOfo0hZJ5WHxCOQR8rp8jb5DICLfhnQAyszIFe+w8c0yVpL3JC/zDdg9wMV+6FKuqmz/wcln4TOv/g0z9vogo6GnuPggdX8mVt+izOaNDACJgdtRh0twmzaJkJACJ2GaGsyPIccbYbDr+jD6+Zsre9QDaal9+AlKODEw/PD9wq3otAAdNfGJD/n2Krsr1ZRy6/2dN2iK9fRCn6s6nGtxaatKEprbsYXhFOfquTw5ss+MDrr4NdxnOyDcw/jS66BUpvJ46M0unU39n/63ucSiWsJmjOHSray5DDaMMNpBOyC/v8IvICHxhVju0XvVzlgkw7rAhhOvDScWMrixKxTmdvCgD2lbrbiTAFEjwkIv+7j+anmr5zqUwvDMbrb5x+K13qu/hdgTqbHRjAD2QdW/n1OC3UKy07MkijfB+EdvIEu3ZRIhDuEUla/gO29XnpRkG5IUPfV2XgbgFS4nFx2e64UGvvoKd7nwkKnfnXHpKKO8Gc+wbys/4AJRjleAct9oDdLRuuCY9gnzzK51mBPG8+6APJu6iqLLoplLI/eYmZS2ekR2WEPi7m0m+4MV2+SZ56mlcM9giO6LjLqNyAi99f1qFtMya9nLWhArD6ZZAM66Luv8fq5b3Rk8mnjrLOiuXXqvDBkqmJKoCOBoLxZCLVo=
  app: soldn-staging
  on:
    repo: dgmstuart/swing-out-london
