language: ruby
cache:
  bundler: true
  yarn: true
  directories:
    - node_modules

addons:
  postgresql: "9.6"

services:
  - postgresql

before_script:
  - yarn install
  - RAILS_ENV=test bundle exec rake db:setup

deploy:
  provider: heroku
  app: soldn-staging
  api_key:
    secure: E8t9jBuXw8+EW3MMwLNxW/YcrSx6sHMiNWXyO7YWj+Y2QzRGblSg5fvPbISJcb530xvWRHEEleSAtdG35pdekZWFPXYREYBR1nXPUTeozceTHmIptpuc192zL4nZusTHh4JU8qAuRS3jmSsN6kgT4CIRR+0wlhVc1Slx3ali2bULv3jpSodukA90WEnCI2TIYqsMulMQmUHxzKB7qzbOzAv/+Z2rqp2xZzLmRc4kbUSjEWnqIREg6tzuNSf8q9eklxJPBVlxOoG0QQrHc/6QW2BxHZ5BA6aCp05PcjzjA2oXMKYf45Arj2VKYjWt9hwUcwx4NWBAufHkceatk368yufMV8Tgl1NvFNiY8kZhGVf9sriqwgqrs8PcYy/P4oTgOIXaW2BSuQMQduQryzJguw5HEaDe4JVQtWUVrABFwSrBucn3QePeivRkWIqcSSEepzTTs7+dmGf/GahYbbN9i5LnQ5jcGdKhMxp+ynfNjUdXjCunPtx6XoWUcZqLxeSBtVPsEDSWVp/UDqfBsK9ImfHCR6h4zi6CsaarANE0uehHSbOagaLg3Pjkegm7iowj1jilcTrSad/Frzh7WygVjMg4Qxf2yM96uQM4o4/Vw1KhD8TbrFXnONxINM8P5lF5s3tMxYlBXxkqGHRr4lr9hqNBgIIL4Oxt488VQPV3Oxo=
