about:
  dir_path: "info/about"
  london:
    content:
      - intro_london
      - goals
      - swing_dancing_in_london
    sidebar:
      - about_us_london
      - about_lindy
      - show_love_london
  bristol:
    content:
      - intro_bristol
      - goals
      - swing_dancing_in_bristol
    sidebar:
      - about_us_bristol
      - about_lindy
      - show_love_bristol

listings_policy:
  dir_path: "info/listings_policy"
  london:
    content:
      - intro_london
      - location_text_london
      - classes_text_london
      - classes_policy
      - socials_text_london
      - socials_policy
      - music_text
    sidebar:
      - swing_music
  bristol:
    content:
      - intro_bristol
      - location_text_bristol
      - classes_text_bristol
      - classes_policy
      - socials_text_bristol
      - socials_policy
      - music_text
    sidebar:
      - swing_music
